### ISSUE TITLE
Crash on some request handling

### ISSUE THREAD

**Issue by Jean-Daniel** [micktwomey/uwsgi_exporter#7]
While fetching metrics from uwsgi exporter, I got 500 errors from time to time and I see this error in the log file:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/var/www/uwsgi/webservices/env/lib/python3.5/site-packages/prometheus_client/exposition.py", line 86, in do_GET
    output = generate_latest(registry)
  File "/var/www/uwsgi/webservices/env/lib/python3.5/site-packages/prometheus_client/exposition.py", line 63, in generate_latest
    for metric in registry.collect():
  File "/var/www/uwsgi/webservices/env/lib/python3.5/site-packages/prometheus_client/core.py", line 97, in collect
    for metric in collector.collect():
  File "/var/www/uwsgi/webservices/env/bin/uwsgi_exporter.py", line 57, in collect
    yield from stats_getter()
  File "/var/www/uwsgi/webservices/env/bin/uwsgi_exporter.py", line 44, in build_prometheus_stats
    for metric_name, labels, value in stats:
  File "/var/www/uwsgi/webservices/env/bin/uwsgi_exporter.py", line 29, in object_to_prometheus
    yield from list_to_prometheus("{}_{}".format(prefix, name), value, labels, name)
  File "/var/www/uwsgi/webservices/env/bin/uwsgi_exporter.py", line 36, in list_to_prometheus
    yield from object_to_prometheus(prefix, stats, labels, label_name)
  File "/var/www/uwsgi/webservices/env/bin/uwsgi_exporter.py", line 29, in object_to_prometheus
    yield from list_to_prometheus("{}_{}".format(prefix, name), value, labels, name)
  File "/var/www/uwsgi/webservices/env/bin/uwsgi_exporter.py", line 36, in list_to_prometheus
    yield from object_to_prometheus(prefix, stats, labels, label_name)
  File "/var/www/uwsgi/webservices/env/bin/uwsgi_exporter.py", line 29, in object_to_prometheus
    yield from list_to_prometheus("{}_{}".format(prefix, name), value, labels, name)
  File "/var/www/uwsgi/webservices/env/bin/uwsgi_exporter.py", line 36, in list_to_prometheus
    yield from object_to_prometheus(prefix, stats, labels, label_name)
  File "/var/www/uwsgi/webservices/env/bin/uwsgi_exporter.py", line 23, in object_to_prometheus
    for name, value in stats_dict.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by Jean-Daniel** [comment]
This is due to uwsgi returning server vars (cores.vars is not empty) from time to time. Probably when querying stats while it is processing an other request.

```json
{
	"version":"2.0.12-debian",
	"listen_queue":0,
	"listen_queue_errors":0,
	"signal_queue":0,
	"load":0,
	"pid":2691,
	"uid":998,
	"gid":998,
	"cwd":"/var/www/uwsgi/webservices/app",
	"locks":[
		{
			"user 0":0
		},
		{
			"signal":0
		},
		{
			"filemon":0
		},
		{
			"timer":0
		},
		{
			"rbtimer":0
		},
		{
			"cron":0
		},
		{
			"rpc":0
		},
		{
			"snmp":0
		}
	],
	"sockets":[
		{
			"name":"/run/uwsgi/app/webservices/socket",
			"proto":"uwsgi",
			"queue":0,
			"max_queue":0,
			"shared":0,
			"can_offload":0
		},
		{
			"name":"/run/uwsgi/app/webservices/socket",
			"proto":"uwsgi",
			"queue":0,
			"max_queue":0,
			"shared":0,
			"can_offload":0
		},
		{
			"name":"10.0.0.10:9090",
			"proto":"uwsgi",
			"queue":0,
			"max_queue":100,
			"shared":0,
			"can_offload":0
		}
	],
	"workers":[
		{
			"id":1,
			"pid":14396,
			"accepting":1,
			"requests":107134,
			"delta_requests":107134,
			"exceptions":1,
			"harakiri_count":0,
			"signals":0,
			"signal_queue":0,
			"status":"idle",
			"rss":0,
			"vsz":0,
			"running_time":2226135605,
			"last_spawn":1493908364,
			"respawn_count":1,
			"tx":25410548,
			"avg_rt":15309,
			"apps":[
				{
					"id":0,
					"modifier1":0,
					"mountpoint":"",
					"startup_time":7,
					"requests":107134,
					"exceptions":1,
					"chdir":""
				}
			],
			"cores":[
				{
					"id":0,
					"requests":107134,
					"static_requests":0,
					"routed_requests":0,
					"offloaded_requests":0,
					"write_errors":1,
					"read_errors":0,
					"in_request":0,
					"vars":[

					]
				}
			]
		},
		{
			"id":2,
			"pid":14397,
			"accepting":1,
			"requests":114055,
			"delta_requests":114055,
			"exceptions":2,
			"harakiri_count":0,
			"signals":0,
			"signal_queue":0,
			"status":"idle",
			"rss":0,
			"vsz":0,
			"running_time":2363305598,
			"last_spawn":1493908364,
			"respawn_count":1,
			"tx":27154389,
			"avg_rt":16161,
			"apps":[
				{
					"id":0,
					"modifier1":0,
					"mountpoint":"",
					"startup_time":7,
					"requests":114055,
					"exceptions":2,
					"chdir":""
				}
			],
			"cores":[
				{
					"id":0,
					"requests":114055,
					"static_requests":0,
					"routed_requests":0,
					"offloaded_requests":0,
					"write_errors":3,
					"read_errors":0,
					"in_request":0,
					"vars":[

					]
				}
			]
		},
		{
			"id":3,
			"pid":14398,
			"accepting":1,
			"requests":143514,
			"delta_requests":143514,
			"exceptions":1,
			"harakiri_count":0,
			"signals":0,
			"signal_queue":0,
			"status":"idle",
			"rss":0,
			"vsz":0,
			"running_time":2944631101,
			"last_spawn":1493908364,
			"respawn_count":1,
			"tx":34031760,
			"avg_rt":15895,
			"apps":[
				{
					"id":0,
					"modifier1":0,
					"mountpoint":"",
					"startup_time":7,
					"requests":143514,
					"exceptions":1,
					"chdir":""
				}
			],
			"cores":[
				{
					"id":0,
					"requests":143514,
					"static_requests":0,
					"routed_requests":0,
					"offloaded_requests":0,
					"write_errors":1,
					"read_errors":0,
					"in_request":0,
					"vars":[

					]
				}
			]
		},
		{
			"id":4,
			"pid":14399,
			"accepting":1,
			"requests":122845,
			"delta_requests":122845,
			"exceptions":5,
			"harakiri_count":0,
			"signals":0,
			"signal_queue":0,
			"status":"busy",
			"rss":0,
			"vsz":0,
			"running_time":2554765244,
			"last_spawn":1493908364,
			"respawn_count":1,
			"tx":29340532,
			"avg_rt":20558,
			"apps":[
				{
					"id":0,
					"modifier1":0,
					"mountpoint":"",
					"startup_time":7,
					"requests":122846,
					"exceptions":5,
					"chdir":""
				}
			],
			"cores":[
				{
					"id":0,
					"requests":122845,
					"static_requests":0,
					"routed_requests":0,
					"offloaded_requests":0,
					"write_errors":5,
					"read_errors":0,
					"in_request":1,
					"vars":[
"QUERY_STRING=",
"REQUEST_METHOD=PUT",
"CONTENT_TYPE=application/json;charset=UTF-8",
"CONTENT_LENGTH=2",
"REQUEST_URI=/webapp/uri",
"PATH_INFO=/webapp/uri",
"DOCUMENT_ROOT=/var/www/default",
"SERVER_PROTOCOL=HTTP/1.1",
"REQUEST_SCHEME=https",
"HTTPS=on",
"REMOTE_ADDR=1.2.3.4",
"REMOTE_PORT=52514",
"SERVER_PORT=443",
"SERVER_NAME=example.com",
"HTTP_ACCEPT_LANGUAGE=fr",
"HTTP_ACCEPT=application/json",
"HTTP_HOST=example.com",
"HTTP_CONTENT_TYPE=application/json;charset=UTF-8",
"HTTP_CONTENT_LENGTH=2",
"HTTP_CONNECTION=Keep-Alive",
"HTTP_ACCEPT_ENCODING=gzip",
""
					]
				}
			]
		}
	]
}
```

**Comment by Jean-Daniel** [comment]
My bad, wrong project. Didn't realize it was the go version here ;-)
